# Generated by Django 2.0.5 on 2018-05-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='博客标题', max_length=50),
        ),
    ]
